project:
  type: website
  output-dir: docs
  

website:
  title: "rhynchambers.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hobbies.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

